# Generated by Django 3.2.10 on 2022-03-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TitlePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlepic', models.ImageField(upload_to='static/titlepic/')),
            ],
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desription', models.CharField(blank=True, max_length=100)),
                ('p1', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p2', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p3', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p4', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p5', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p6', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p7', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p8', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p9', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p10', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p11', models.ImageField(blank=True, upload_to='static/pics/')),
                ('p12', models.ImageField(blank=True, upload_to='static/pics/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katbez.titlegallery')),
            ],
        ),
    ]
